on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.5.0
        with:
          # URL of the project to add issues to
          project-url: https://github.com/users/dnoenickx/projects/2
          # A GitHub personal access token with write access to the project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
